[package]
name = "mirl_windowing"
version = "0.0.0-alpha"
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

# This is a neat tool we will use later
# [target.'cfg(all(not(target_arch = "wasm32")))'.dependencies]

[features]
default = ["std"]
# Core
std = [
    "bitcode?/std",
    "mirl_buffer/std",
    "mirl_extensions/std",
    "mirl_windowing_core/std",
    "serde?/std",
    "strum?/std",
    "wincode?/std",
    "zerocopy?/std",
]
_checking = ["all", "cursor_show_hotspot"]
all = [
    "glfw",
    "minifb",
    "console",
    "all_codecs",
    "all_enum_extensions",
    "image_support",
    "mirl_buffer/all",
    "mirl_extensions/all",
    "mirl_windowing_core/all",
    "mirl_windowing_console?/all",
    "mirl_windowing_glfw?/all",
    "mirl_windowing_minifb?/all",
]
# Does nothing by itself. Needs another codec or enum flag to do something
mirl_derive = [
    "dep:mirl_derive",
    "mirl_buffer/mirl_derive",
    "mirl_windowing_core/mirl_derive",
]
# Compatibility with ffi
c_compatible = [
    "mirl_derive",
    "mirl_buffer/c_compatible",
    "mirl_extensions/c_compatible",
    "mirl_windowing_core/c_compatible",
    "mirl_windowing_console?/c_compatible",
    "mirl_windowing_glfw?/c_compatible",
    "mirl_windowing_minifb?/c_compatible",
]
# Enables all codecs
all_codecs = [
    "serde",
    "bitcode",
    "wincode",
    "compactly",
    "zerocopy",
    "mirl_buffer/all_codecs",
    "mirl_windowing_core/all_codecs",
]
# All enum extensions
all_enum_extensions = ["strum", "enum_ext", "mirl_windowing_core/all_enum_extensions"]
# Codec stuff
serde = [
    "dep:serde",
    "mirl_derive",
    "mirl_windowing_core/serde",
    "bitcode?/serde",
    "mirl_buffer/serde",
]
bitcode = [
    "dep:bitcode",
    "mirl_derive",
    "mirl_windowing_core/bitcode",
    "mirl_buffer/bitcode",
]
wincode = [
    "dep:wincode",
    "mirl_derive",
    "mirl_windowing_core/wincode",
    "mirl_buffer/wincode",
]
compactly = [
    "dep:compactly",
    "mirl_derive",
    "mirl_windowing_core/compactly",
    "mirl_buffer/compactly",
]
zerocopy = [
    "dep:zerocopy",
    "mirl_derive",
    "mirl_windowing_core/zerocopy",
    "mirl_buffer/zerocopy",
]
# Enum extensions
strum = ["dep:strum", "mirl_derive", "mirl_windowing_core/strum"]
enum_ext = ["dep:enum_ext", "mirl_derive", "mirl_windowing_core/enum_ext"]
# Frameworks
## Framework backend using minifb
minifb = ["mirl_windowing_minifb"]
## Framework backend using glfw
glfw = ["mirl_windowing_glfw", "mirl_extensions/glfw"]
## Framework backend using the console
console = ["mirl_windowing_console"]
# keyboard_query = ["mirl_windowing_core/keyboard_query"]
cursor_show_hotspot = [
    "mirl_windowing_core/cursor_show_hotspot",
    "mirl_windowing_glfw?/cursor_show_hotspot",
    "mirl_windowing_minifb?/cursor_show_hotspot",
]
image_support = ["dep:image"]

[dependencies]
bitcode = { version = "0.6", optional = true, default-features = false, features = [
    "derive",
] }
# Codec
compactly = { version = "0.1", optional = true }
enum_ext = { version = "0.6", optional = true, default-features = false }
image = { version = "0.25", optional = true, default-features = false }
mirl_buffer = { version = "0.0.0-alpha" }
mirl_derive = { version = "0.0.0-alpha", optional = true }
# Normal
mirl_extensions = { version = "0.0.0-alpha" }
mirl_windowing_core = { version = "0.0.0-alpha" }
serde = { version = "1.0", optional = true, default-features = false, features = [
    "derive",
] }
# Enum functionality
strum = { version = "0.28", optional = true, default-features = false, features = [
    "derive",
] }
wincode = { version = "0.5", optional = true, features = ["derive"] }
zerocopy = { version = "0.8", optional = true, default-features = false, features = [
    "float-nightly",
    "derive",
] }
[target.'cfg(all(not(target_arch = "wasm32")))'.dependencies]
mirl_windowing_console = { version = "0.0.0-alpha", optional = true }
mirl_windowing_glfw = { version = "0.0.0-alpha", optional = true }
mirl_windowing_minifb = { version = "0.0.0-alpha", optional = true }

[build-dependencies]
mirl_build_tools = { workspace = true }

[lints]
workspace = true
